### ISSUE TITLE
Salting doesn't work with vectors

### ISSUE THREAD

**Issue by Ironholds** [jeroenooms/openssl#10]
> md5(c("foo","bar"))
[1] "acbd18db4cc2f85cedef654fccc4a4d8" "37b51d194a7513e45b56f6524f2d51f2"
> md5(c("foo","bar"),"baz")
[1] "73feffa4b7f6bb68e44cf984c85f6e88"

**Comment by jeroenooms** [comment]
Fixed @ https://github.com/jeroenooms/openssl/commit/53174f8dedc3c0221b37d86628b7183554231b79. Can you verify?

**Comment by Ironholds** [comment]
Verified! Works great :)

**Comment by jeroenooms** [comment]
not sure how i missed that

**Comment by Ironholds** [comment]
I'll add a to-do for me to write a unit test covering it, just in case there are future regressions of some kind.
