### ISSUE TITLE
Can rsa_keygen and friends take a password argument

### ISSUE THREAD

**Issue by richfitz** [jeroenooms/openssl#16]
Your `openssl::read_key` function accepts a string or callback as an argument to unlock a key with a password, perhaps `rsa_keygen` (and other `_keygen` functions) could take a similar password argument to generate a password with a phrase?

**Comment by jeroenooms** [comment]
The password is added on the level of the `pem` encoding. To create a password protected key:

```r
library(openssl)
key <- rsa_keygen()
write_pem(key, "mykey.pem", password = "supersecret")
```

Now if you try to read the key from the pem file you will be asked for the password:

```r
read_key("mykey.pem")
```

**Comment by richfitz** [comment]
Oh, thanks! I wondered if I was being dense.  Could I suggest you add that to the help file `?rsa_keygen`

**Comment by jeroenooms** [comment]
Sure, I accept PR's :)

**Comment by richfitz** [comment]
I'll see what I can do.

**Comment by jeroenooms** [comment]
Closed https://github.com/jeroenooms/openssl/commit/dc6e2e3baa69d0d3e8727414ea33c35c33757832. Thanks for the suggestion.
