### ISSUE TITLE
Export fingerprint?

### ISSUE THREAD

**Issue by richfitz** [jeroenooms/openssl#17]
Any chance you could export the [fingerprint function](https://github.com/jeroenooms/openssl/blob/07a28bf1283a2a38ba09f2771d657ba33d84f5d8/R/openssh.R#L1)?  I have a use case where being able to get the hash of a public key would be useful.

**Comment by jeroenooms** [comment]
In the latest dev version of the package you can use `as.list` on the pubkey to get its fingerprint:

```r
key <- rsa_keygen()
pubkey <- as.list(key)$pubkey
as.list(pubkey)$fingerprint
```

Does that help?

**Comment by jeroenooms** [comment]
edit: actually this already works in the cran version

**Comment by richfitz** [comment]
OK, brilliant.  That's all I need.

**Comment by jeroenooms** [comment]
Can I know your use case? Note that this fingerprint is the `md5` hash of the **ssh** pubkey, which is the thing that you see in your ssh client. But some other systems might use a different algorithm to derive a fingerprint...

**Comment by richfitz** [comment]
This is for the data encryption package (https://github.com/dide-tools/encryptr) - I want something that I can use for the filename of a public key and user-specific encrypted data key that is somewhat collision resistant and repeatable.  So the fingerprint is nice because I can go from the users public key to the appropriate filename.
