### ISSUE TITLE
openssl installation failed on Suse Linux 11SP2 

### ISSUE THREAD

**Issue by zqkal** [jeroenooms/openssl#23]
OS suse Linux 11SP2

I am trying to install the openssl package and running into issues. I have setup the Path variable as per the instructions but still getting the same error. Please advise.
 
Paths:
k2uahp@algrid-ap01:~> echo $PKG_CONFIG_PATH
/usr/lib64/pkgconfig/openssl.pc
k2uahp@algrid-ap01:~> echo $PATH|grep pkg-config
/usr/bin/pkg-config:/usr/fnma/bin:/bin:/usr/bin:/usr/SYSADM/bin:/appl/tools/R2/bin:/appl/tools/R2/bin:/appl/tools/R2/bin
k2uahp@algrid-ap01:~>
 
Error:
 
2016-04-25 17:37:49 (2.63 MB/s) - `/tmp/Rtmpy3rxM0/downloaded_packages/openssl_0.9.2.tar.gz' saved [882041/882041]
 
* installing *source* package ‘openssl’ ...
** package ‘openssl’ successfully unpacked and MD5 sums checked
Found pkg-config cflags and libs!
Using PKG_CFLAGS=
Using PKG_LIBS=-lssl -lcrypto -ldl -lz
------------------------- ANTICONF ERROR ---------------------------
Configuration failed because openssl was not found. Try installing:
* deb: libssl-dev (Debian, Ubuntu, etc)
* rpm: openssl-devel (Fedora, CentOS, RHEL)
* csw: libssl_dev (Solaris)
* brew: openssl (Mac OSX)
If openssl is already installed, check that 'pkg-config' is in your
PATH and PKG_CONFIG_PATH contains a openssl.pc file. If pkg-config
is unavailable you can set INCLUDE_DIR and LIB_DIR manually via:
R CMD INSTALL --configure-vars='INCLUDE_DIR=... LIB_DIR=...'
--------------------------------------------------------------------
ERROR: configuration failed for package ‘openssl’
* removing ‘/home/k2uahp/R/x86_64-pc-linux-gnu-library/3.2/openssl’
 
The downloaded source packages are in
        ‘/tmp/Rtmpy3rxM0/downloaded_packages’
Warning message:
In install.packages("openssl") :
  installation of package ‘openssl’ had non-zero exit status

---------------------------
 openssl version -a
OpenSSL 0.9.8j-fips 07 Jan 2009
built on: Wed Jun  4 12:08:22 UTC 2014
platform: linux-x86_64
options:  bn(64,64) md2(int) rc4(16x,int) des(idx,cisc,4,long) blowfish(ptr2)
compiler: gcc -fPIC -DOPENSSL_PIC -DZLIB -DOPENSSL_THREADS -D_REENTRANT -DDSO_DLFCN -DHAVE_DLFCN_H -DL_ENDIAN -DMD32_REG_T=int -fmessage-length=0 -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector -funwind-tables -fasynchronous-unwind-tables -g -fomit-frame-pointer -fno-strict-aliasing -DTERMIO -Wall -fstack-protector -Wa,--noexecstack -fprofile-use  -DOPENSSL_BN_ASM_MONT -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DMD5_ASM -DAES_ASM
OPENSSLDIR: "/etc/ssl"

**Comment by jeroenooms** [comment]
You need openssl 1.0 or greater. See also the system requirements on the [cran page](https://cran.r-project.org/web/packages/openssl/index.html). 

In addition: usually you shouldn't have to set `PKG_CONFIG_PATH` if you use the system `pkg-config`. But if you do set it, it must be a path (not the pc file) e.g.: `PKG_CONFIG_PATH=/usr/lib64/pkgconfig`

**Comment by zqkal** [comment]
Thank you so much for the prompt response. 

Kalkidan Lebeta
Thanks
