### ISSUE TITLE
Linking to openssl from other R package

### ISSUE THREAD

**Issue by rubak** [jeroenooms/openssl#27]
I'm looking into porting Google's C++ library s2-geometry to R from [this GitHub fork](https://github.com/micolous/s2-geometry-library). It requires the openssl library to compile and I was wondering whether I could benefit from depending on your openssl package?
If I know the user has your package installed it means that openssl is somewhere on their system. Is there then an easy way to for me to link against the library or do I still have to basically copy your configure script and Makevars files and add my own stuff to that? I've never tried to include an existing C++ library in an R package, so I'm a bit in the dark here, and any advice you can give is highly appreciated.

**Comment by jeroenooms** [comment]
The `openssl` R package does not expose any C bindings so that won't help you. You'll just have to check for libssl in your package configure script.

**Comment by rubak** [comment]
OK. Thanks for the quick reply. What is the correct way to attribute you if I end up using a modified version of your configure script? Simply as 'ctb' in the package description file?
