### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by dwaggott** [jeroenooms/openssl#28]
Does this look familiar? libssl and headers should be installed. I don't see any other errors.

```
** testing if installed package can be loaded
Error in dyn.load(file, DLLpath = DLLpath, ...) : 
  unable to load shared object '/home/xxx/R/x86_64-pc-linux-gnu-library/3.2/openssl/libs/openssl.so':
  libssl.so.1.0.0: cannot open shared object file: No such file or directory
Error: loading failed
```

**Comment by jeroenooms** [comment]
Can you show me installation output? Is your `libssl` in an unusual directory? In that case you might need to set `LD_LIBRARY_PATH`.

**Comment by dwaggott** [comment]
[openssl_install.log](https://gist.github.com/150473f1a7a718dee5ef421777b6a024)

$ ldconfig -p | grep libssl
        libssl3.so (libc6,x86-64) => /usr/lib64/libssl3.so
        libssl.so.10 (libc6,x86-64) => /usr/lib64/libssl.so.10
        libssl.so (libc6,x86-64) => /usr/lib64/libssl.so

**Comment by jeroenooms** [comment]
Is there an additional `openssl` on this box? What do you get for: `pkg-config --cflags --libs openssl` ?

**Comment by jeroenooms** [comment]
Which OS is this?

**Comment by dwaggott** [comment]
centos kernel 2.6

**Comment by jeroenooms** [comment]
Which version of centos is that? What do you get for: `pkg-config --cflags --libs openssl` ?

**Comment by dwaggott** [comment]
pkg-config --cflags --libs openssl
-I/home/dwaggott/.linuxbrew/Cellar/openssl/1.0.2d_1/include -L/home/dwaggott/.linuxbrew/Cellar/openssl/1.0.2d_1/lib -lssl -lcrypto

# Looks like it's based off RedHat 4..4. Not completely sure, this is an HPC.
cat /proc/version
Linux version 2.6.32-573.12.1.el6.x86_64 (mockbuild@c6b8.bsys.dev.centos.org) (gcc version 4.4.7 20120313 (Red Hat 4.4.7-16) (GCC) ) #1 SMP Tue Dec 15 21:19:08 UTC 2015

**Comment by jeroenooms** [comment]
If that's where your libs are you need to set (at all time) an environment variable:
```
export LD_LIBRARY_PATH=/home/dwaggott/.linuxbrew/lib
```

**Comment by jeroenooms** [comment]
Is this fixed?

**Comment by dwaggott** [comment]
Yes, please close. It was related to a conflict with linuxbrew paths.
