### ISSUE TITLE
Compiling with icc on linux

### ISSUE THREAD

**Issue by BertrandServin** [jeroenooms/openssl#31]
Hello,

I am trying to install the package from source on Debian testing. My R install is built with the Intel Compiler rather than gcc. Installation of the openssl package fails with many errors (see attached file) in particular this one :
`
In file included from /usr/include/resolv.h(65),
                 from ssl.c(15):
/usr/include/arpa/nameser.h(115): error: identifier "u_char" is undefined
        const u_char    *_msg, *_eom;
  
`

I am not sure what's going on here ...

[compil-openssl.log.txt](https://github.com/jeroenooms/openssl/files/441828/compil-openssl.log.txt)

**Comment by jeroenooms** [comment]
Can you please test if this problem has already been solved in the dev version:

```r
install.packages("https://github.com/jeroenooms/openssl/archive/master.tar.gz", repos = NULL)
```

**Comment by BertrandServin** [comment]
Yep, that works ! Thanks for the quick response !
