### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by agl** [jeroenooms/openssl#40]
[CRAN metadata](https://cran.r-project.org/web/packages/openssl/index.html) lists this package as having an MIT license. However, the LICENSE file just lists the year and author. To clarify this, would it be possible to include the [text of the MIT license](https://opensource.org/licenses/MIT) in the LICENSE file or perhaps in a COPYING file?

(I note that CRAN says that [LICENSE should just be a template](https://opensource.org/licenses/MIT). However, if you [download](https://cran.r-project.org/src/contrib/openssl_0.9.6.tar.gz) this package from CRAN, the template isn't expanded.)

**Comment by jeroenooms** [comment]
There is also a [COPYING](https://github.com/jeroenooms/openssl/blob/master/COPYING) file now.
