### ISSUE TITLE
Checks for release on CRAN

### ISSUE THREAD

**Issue by Ironholds** [jeroenooms/openssl#9]
With the functionality expansion, we should throw the new version up on CRAN so people can start using it. I need to go through and check all the documentation and tests first, just to be sure it's spiffy. This is a note to me to do this.

**Comment by jeroenooms** [comment]
I'll push out a version this week. I added support for stream hashing btw (via connections)

**Comment by Ironholds** [comment]
Yay!

On Monday, 5 January 2015, Jeroen Ooms <notifications@github.com> wrote:

> I'll push out a version this week. I added support for stream hashing btw
> (via connections)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jeroenooms/openssl/issues/9#issuecomment-68782462>.
>


-- 
Sent from my mobile computing device of Lovecraftian complexity and horror.

**Comment by jeroenooms** [comment]
Its on cran now. I also added a quick vignette: http://cran.r-project.org/web/packages/openssl/vignettes/crypto_hashing.html
